# syntax=docker/dockerfile:1

FROM node:22-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /app

FROM base AS deps
COPY . .
RUN pnpm install --frozen-lockfile

FROM deps AS builder

# Build-time environment variables (injected by Coolify via --build-arg)
ARG CI
ARG COOLIFY_BRANCH
ARG COOLIFY_FQDN
ARG COOLIFY_RESOURCE_UUID
ARG COOLIFY_URL
ARG DATABASE_URL
ARG BETTER_AUTH_SECRET
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG DISCORD_CLIENT_ID
ARG DISCORD_CLIENT_SECRET
ARG GITHUB_CLIENT_ID
ARG GITHUB_CLIENT_SECRET
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_SENDER
ARG SMTP_USERNAME
ARG SMTP_PASSWORD
ARG SMTP_SECURE
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_DIST_DIR
ARG NODE_ENV=production
ARG PORT=3000
ARG ORPC_DEV_DELAY_MS=0
ARG SOCKET_PORT=4000
ARG REACT_EDITOR

# Make build args available as environment variables during the build
ENV CI=$CI \
    COOLIFY_BRANCH=$COOLIFY_BRANCH \
    COOLIFY_FQDN=$COOLIFY_FQDN \
    COOLIFY_RESOURCE_UUID=$COOLIFY_RESOURCE_UUID \
    COOLIFY_URL=$COOLIFY_URL \
    DATABASE_URL=$DATABASE_URL \
    BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET \
    GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID \
    GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET \
    DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID \
    DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET \
    GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID \
    GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET \
    SMTP_HOST=$SMTP_HOST \
    SMTP_PORT=$SMTP_PORT \
    SMTP_SENDER=$SMTP_SENDER \
    SMTP_USERNAME=$SMTP_USERNAME \
    SMTP_PASSWORD=$SMTP_PASSWORD \
    SMTP_SECURE=$SMTP_SECURE \
    NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL \
    NEXT_DIST_DIR=$NEXT_DIST_DIR \
    NODE_ENV=$NODE_ENV \
    PORT=$PORT \
    ORPC_DEV_DELAY_MS=$ORPC_DEV_DELAY_MS \
    SOCKET_PORT=$SOCKET_PORT \
    REACT_EDITOR=$REACT_EDITOR

RUN pnpm run build

FROM base AS runner
COPY --from=builder /app /app
WORKDIR /app
EXPOSE 3000 3001 4000
HEALTHCHECK --interval=10s --timeout=5s --start-period=5s --retries=3 \
  CMD curl -fsS http://localhost:3000/api/rpc/health || exit 1
CMD ["pnpm", "run", "start"]
