// Generated by scripts/generate-sri.js. Do not edit by hand.
export const SCALAR_VERSION = "1.25.0";
export const SCALAR_URL =
  "https://cdn.jsdelivr.net/npm/@scalar/api-reference@1.25.0/dist/browser/standalone.js";
export const SCALAR_SRI =
  "sha384-aYYa3Qxeo6+Z48D3AmUywxDcZRSrJHutGAgpJiBtkiofix52Px1F0p8tFptEbnNX";
